### ISSUE TITLE
Catboost Blend

### ISSUE THREAD

**Issue by rajat5ranjan** [dubinich/ltfs-finhack-solution#1]
Hey dubinich,

I was going through the solution, didn't find where you have blended LGBM model with Catboost?

Thanks for having my query!!

Regards
Rajat

**Comment by dubinich** [comment]
I just posted the general approach with LGBM example. For catboost I used same features.
Blending was done in another notebook :)
Maybe I'll add it later to the repository.

**Comment by rajat5ranjan** [comment]
Sure, thanks
